version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME}/devops-backend-cd:latest
    container_name: backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL=mongodb+srv://todolist:reverse@dbreversetodolist.32f5n.mongodb.net/?retryWrites=true&w=majority&appName=DBReverseTodoList
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://localhost:3001
    image: ${DOCKER_USERNAME}/devops-frontend-cd:latest
    container_name: frontend
    restart: always
    ports:
      - "3000:5000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge